kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secondary-scheduler-operator
rules:
- apiGroups:
  - operator.openshift.io
  resources:
  - secondaryschedulers
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - configmaps
  - events
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
